import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

print(np.power(arr1,arr2))
print(np.floor_divide(arr1,arr2))
print(np.bitwise_and(arr1,arr2))
print(np.bitwise_or(arr1,arr1))
print(np.bitwise_xor(arr1,arr2))
print(np.bitwise_not(arr1))
print(np.logical_and(arr1,arr2))
print(np.logical_or(arr1,arr2))
print(np.logical_not(arr1))
print(np.logical_xor(arr1,arr2))

print(np.equal(arr1,arr2))
print(np.not_equal(arr1,arr2))
print(np.absolute(arr1))
